apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.name }}
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "30020"
  HOST: "0.0.0.0"
  DB: "Stagging-activity"
