apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "30027"
  HOST: "0.0.0.0"
  DB: "Stagging-personalisation"
  ON_BOARDING_ASSESSMENT_COMPLETE_EVENT: "staging_on_boarding_assessment_complete"
  VIWELL_ASSESSMENT_COMPLETE_EVENT: "staging_viwell_assessment_complete"
  CHECKIN_DONE_EVENT: "staging_checkin_done"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "2"
  
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
