name: loyalty
replicaCount: 1
AppVersion: prod-b82424f

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/loyalty
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30021
  targetport: 30021

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage:
namespace: 'sec'

##for liveness and readiness
path: '/health'
port: 30021
