apiVersion: v1
data:
  # ENV: 'dev'
  
 
  # DYNAMIC_LINK_DOMAIN_URI_PREFIX: 'link.viwell.app'
  # USER_STORE_DB: 'viwell-user-store'
  # SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  # SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  # VAR: 'INPUT'
  # PORT: '3009'
  # HOST: '0.0.0.0'
  # DB: 'viwell-pillar'
  # SEND_UPDATE_PILLAR_EVENT: "dev_send_update_pillar_event"
  # SEND_DEACTIVATE_PILLAR_EVENT: "dev_send_deactivate_pillar_event"
  # KAFKA_CONSUMER_GROUP_ID: 'dev_pillar'

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
