apiVersion: v1
data:
  VAR: "INPUT"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  DB: "viwell-notification"
  SEND_DELETE_COLLECTION_CATEGORY: "send_delete_collection_category"
  SEND_UPDATE_CLIENT_EVENT: "send_update_client_event"
  NODE_ENV: "false"
  
  
