name: thryve-redirect
replicaCount: 1
AppVersion: "5138220"

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/thryve-redirect
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 8080
  targetport: 8080

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage:
namespace: 'prod'

##for liveness and readiness
path: '/health'
port: 8080