name: review
replicaCount: 1
AppVersion: prod-stagging-33ce15e-22

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/review
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 3006
  targetport: 3006

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage:
namespace: 'prod'

##for liveness and readiness
path: '/health'
port: 3006
