apiVersion: v1
data:
  ENV: 'dev'
  
 
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: 'link.viwell.app'
  USER_STORE_DB: 'viwell-user-store'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  VAR: 'INPUT'
  PORT: '30015'
  HOST: '0.0.0.0'
  DB: 'viwell-favorite'
  CONTENT_UPDATED_EVENT: "dev_content_updated"
  KAFKA_CONSUMER_GROUP_ID: 'dev_favorite'

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
