apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "80"
  HOST: "0.0.0.0"
  JwtIss: viwell.app
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "4"
  RabbitTimeout: "10000"
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: "link.viwell.app"
  USER_STORE_DB: "viwell-user-store"
  AdminHost: "portal-staging.viwell.app"





kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
