apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "30012"
  HOST: "0.0.0.0"
  DB: "Stagging-avatar"
  SEND_DEACTIVATE_AVATAR_EVENT: "staging_send_deactivate_avatar_event"
  SEND_UPDATE_AVATAR_EVENT: "staging_send_update_avatar_event"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "4" 
  AdminHost: 'portal-staging.viwell.app'
  RabbitTimeout: '10000'
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: 'link.viwell.app'
  USER_STORE_DB: 'viwell-user-store'

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
