apiVersion: v1
data:
  VAR: "INPUT"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
   AdminHost: "portal.viwell.app"
   JwtSecret: "JWT-Super-Secret"
   JwtIss: "viwell.app"
   DB: "viwell-auth"
   DYNAMIC_LINK_DOMAIN_URI_PREFIX: "https://link.viwell.app"
   RabbitTimeout: "10000"
   SEND_DELETE_COLLECTION_CATEGORY: "send_delete_collection_category"
   SEND_UPDATE_CLIENT_EVENT: "send_update_client_event"
