name: activity2
replicaCount: 1
AppVersion: "e3d207a-45"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/activity2
  pullPolicy: IfNotPresent
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 50060
  targetport: 50060

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'dev'

##for liveness and readiness
path: '/health'
port: 50060
