apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "30043"
  HOST: "0.0.0.0"
  DB: "Stagging-reward-partner"
  ENV: "staging"
  S3_Bucket: "image-resize-stagging-814880204573-us-east-1"
  S3_Region: "us-east-1"
  GLOBAL_OBJECT_STORAGE_BUCKET_NAME: "image-resize-stagging-814880204573-us-east-1"
  GLOBAL_OBJECT_STORAGE_REGION: "us-east-1"
  KSA_OBJECT_STORAGE_BUCKET_NAMESPACE: "axzsfqzecwcx"
  KSA_OBJECT_STORAGE_BUCKET_NAME: "bucket-20230524-1613"
  KSA_OBJECT_STORAGE_REGION: "me-jeddah-1"
  SEND_TIER_UPDATE_EVENT: "staging_send_tier_update"

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
