apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'ksa-dev'
  AdminHost: 'portal-dev-b.viwell.app'
  RabbitTimeout: '10000'
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: 'link.viwell.app'
  USER_STORE_DB: 'viwell-user-store'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  VAR: 'INPUT'
  PORT: '30040'
  HOST: '0.0.0.0'
  DB: 'dev_b_wearable'
  S3_Bucket: 'image-resize-dev-814880204573-us-east-1'
  S3_Region: 'us-east-1'
  apiUrl: 'https://api.und-gesund.de/v5/'
  ContentType: 'application/x-www-form-urlencoded'
  AppID: '8DlPLJh4HTz7K5la'
  THRYVE_AppID: '8DlPLJh4HTz7K5la'
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "5"
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
