apiVersion: v1
data:
  VAR: "INPUT"
  SQL_DB_NAME: "staging_aggregates"
  ENV: "stagging"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "4"
  LOG_TOPIC: "staging_topic_log"
  KAFKA_CONSUMER_GROUP_ID_1: "staging_aggregates_2"
  
kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
