apiVersion: v1
data:
  VAR: "INPUT"
  SQL_DB_NAME: "staging_aggregates"
  ENV: "stagging"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "4"
  LOG_TOPIC: "staging_log_topic"
  KAFKA_CONSUMER_GROUP_ID: "staging_aggregates"
kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
