apiVersion: v1
data:
  ENV: "dev"
 


  USER_STORE_DB: "viwell-user-store"


  VAR: "INPUT"
  PORT: "3001"
  HOST: "0.0.0.0"
  DB: "viwell-auth"
 
  JwtIss: "viwell.com"
  SEND_DEACTIVATE_AVATAR_EVENT: "dev_send_deactivate_avatar_event"
  SEND_UPDATE_AVATAR_EVENT: "dev_send_update_avatar_event"
  SEND_UPDATE_CLIENT_EVENT: "dev_send_update_client_event"
  USER_DELETED_EVENT: "dev_user_deleted"
  EMPLOYEE_PROFILE_COMPLETED_EVENT: "dev_employee_profile_completed"
  KAFKA_LOYALTY_ADD_POINTS: 'dev_loyalty_add_points'
  KAFKA_CONSUMER_GROUP_ID: 'dev_auth'

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
