apiVersion: v1
data:
  VAR: "INPUT"
  PORT: "3001"
  HOST: "0.0.0.0"
  DB: "viwell-auth"
  AdminHost: "portal-dev.viwell.app"
  JwtIss: "viwell.com"
  

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
