name: notification
replicaCount: 1
AppVersion: prod-stagging-9836909-31

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/notification
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 3002
  targetport: 3002

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage:
namespace: 'sec'

##for liveness and readiness
path: '/health'
port: 3002
