apiVersion: v1
data:
  ENV: "dev"
 


  USER_STORE_DB: "viwell-user-store"


  VAR: "INPUT"
  PORT: "30026"
  HOST: "0.0.0.0"
  DB: "viwell-report"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
