apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "30013"
  HOST: "0.0.0.0"
  NODE_ENV: "false"
  DB: "Stagging-rbac"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "2"
  
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
