apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  RabbitTimeout: '15000'
  USER_STORE_DB: 'Stagging-user-store'
  AdminHost: 'portal-staging.viwell.app'
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: 'link.viwell.app'
  PORT: "30024"
  HOST: "0.0.0.0"
  DB: "Stagging-progress"
  SEND_UPDATE_CATEGORY_EVENT: "staging_send_update_category_event"
  CONTENT_UPDATED_EVENT: "staging_content_updated"
  COLLECTION_UPDATED_EVENT: "staging_collection_updated"
  TOGGLE_CONTENT_STATUS_EVENT: "staging_toggle_content_status"
  EMPLOYEE_PROFILE_COMPLETED_EVENT: "staging_employee_profile_completed"
  KAFKA_ADD_WEARABLE_PROGRESS_TRACKING: 'staging_progress_add_wearable_tracking'
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "4"
  LOG_TOPIC: "staging_topic_log"

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
