apiVersion: v1
data:
  ENV: "dev"
 


  USER_STORE_DB: "viwell-user-store"


  VAR: "INPUT"
  PORT: "30043"
  HOST: "0.0.0.0"
  DB: "viwell-reward-partner"
  ENV: "dev"
  S3_Bucket: "image-resize-dev-814880204573-us-east-1"
  S3_Region: "us-east-1"
  GLOBAL_OBJECT_STORAGE_BUCKET_NAME: "image-resize-dev-814880204573-us-east-1"
  GLOBAL_OBJECT_STORAGE_REGION: "us-east-1"
  KSA_OBJECT_STORAGE_BUCKET_NAMESPACE: "axzsfqzecwcx"
  KSA_OBJECT_STORAGE_BUCKET_NAME: "bucket-20230524-1613"
  KSA_OBJECT_STORAGE_REGION: "me-jeddah-1"
  SEND_TIER_UPDATE_EVENT: "dev_send_tier_update"
  LOG_TOPIC: "dev_log_topic"
  
kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
