apiVersion: v1
data:
  VAR: "INPUT"
  KAFKA_HEARTBEAT_INTERVAL: "30000"
  KAFKA_SESSION_TIMEOUT: "180000"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
