name: presenter
replicaCount: 1

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/presenter
  pullPolicy: Always
  tag: ""

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30031
  targetport: 30031

# resources: 
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:   
namespace: "ksa-dev"
  
##for liveness and readiness
path: "/health"
port: 30031


