name: organization
replicaCount: 1
AppVersion: prod-stagging-d74636b-74

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/organization
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30014
  targetport: 30014

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage:
namespace: 'sec'

##for liveness and readiness
path: '/health'
port: 30014
