apiVersion: v1
data:
  ENV: "dev"
  VAR: "INPUT"
  PORT: "30044"
  HOST: "0.0.0.0"
  SQL_DB_NAME: "staging_streak"
  PGDATABASE: "staging_streak"
  LOG_TOPIC: "staging_log_topic"
  KAFKA_CONSUMER_GROUP_ID: "staging_streak-quest"
  DISABLE_FOR_KSA: "true"
  
  
kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
