name: loyalty
replicaCount: 1
AppVersion: "dev-103d4db-127"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/loyalty
  pullPolicy: IfNotPresent
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30021
  targetport: 30021

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
namespace: 'dev'

##for liveness and readiness
path: '/health'
port: 30021
