apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sec-tag
  namespace: 'argocd'
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: 'sec'
    server: 'https://18BD766DF4B9BCA88A6E5414D08FCF69.gr7.me-central-1.eks.amazonaws.com'
  source:
    path: sec-uae/Helm-charts/tag
    repoURL: 'git@github.com:VIWELL-Tech/devops-argocd.git'
    targetRevision: main
  sources: []
  project: 'sec'
