name: assessment-v2
replicaCount: 2
AppVersion: prod-stagging-807b865-159

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/assessment-v2
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30033
  targetport: 30033

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'prod'

##for liveness and readiness
path: '/health'
port: 30033
