apiVersion: v1
data:
  # ENV: "dev"
 


  # USER_STORE_DB: "viwell-user-store"


  # VAR: "INPUT"
  # ENV: "dev"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
