name: wearable
replicaCount: 3
AppVersion: prod-stagging-7c990bb-65

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/wearable
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30040
  targetport: 30040

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage:
namespace: 'prod'

##for liveness and readiness
path: '/health'
port: 30040
