name: favorite
replicaCount: 1
AppVersion: prod-stagging-b94554f-31

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/favorite
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30015
  targetport: 30015

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage:
namespace: 'sec'

##for liveness and readiness
path: '/health'
port: 30015
