apiVersion: v1
data:
  VAR: "INPUT"
  SQL_DB_NAME: "staging_aggregates"
  ENV: "stagging"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "4"
  KAFKA_CONSUMER_GROUP_ID: "staging_presenter"
  

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
