name: assessment-v2
replicaCount: 1
AppVersion: "d1a9e69"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/assessment-v2
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30033
  targetport: 30033

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
namespace: 'dev'

##for liveness and readiness
path: '/health'
port: 30033
