name: assessmentv2shadow
replicaCount: 1
AppVersion: "stagging-d4bc693-141"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/assessment-v2
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30033
  targetport: 30300

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'prod'

##for liveness and readiness
path: '/health'
port: 30300
