name: wearable-connect
replicaCount: 3
AppVersion: "stagging-d6cd924-15"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/wearable-connect
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30050
  targetport: 30050

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'stagging'

##for liveness and readiness
path: '/health'
port: 30050
