name: reward-partner
replicaCount: 1
AppVersion: prod-latest
image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/reward-partner
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30043
  targetport: 30043

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
namespace: 'sec'

##for liveness and readiness
path: '/health'
port: 30043
