name: organization
replicaCount: 1
AppVersion: "ksa-dev-7deec34-19"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/organization
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30014
  targetport: 30014

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
namespace: 'ksa-dev'

##for liveness and readiness
path: '/health'
port: 30014
