apiVersion: v1
data:
  VAR: "INPUT"
  PORT: "30020"
  HOST: "0.0.0.0"
  DB: "viwell-activity"
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: "https://link.viwell.app"
  AdminHost: "portal-dev.viwell.app"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
