apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stagging-email
  namespace: 'argocd'
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: 'stagging'
    server: 'https://kubernetes.default.svc'
  source:
    path: stagging/Helm-charts/email
    repoURL: 'git@github.com:VIWELL-Tech/devops-argocd.git'
    targetRevision: main
  sources: []
  project: 'default'
