apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'ksa-dev'
  AdminHost: "portal-dev-b.viwell.app"
  RabbitTimeout: "10000"
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: "link.viwell.app"
  USER_STORE_DB: "viwell-user-store"
  SEND_DELETE_COLLECTION_CATEGORY: "send_delete_collection_category"
  SEND_UPDATE_CLIENT_EVENT: "send_update_client_event"
  VAR: "INPUT"
  EmailHost: "email-smtp.us-east-2.amazonaws.com"
  EmailPort: "465"
  EmailAccountType: "SES"
  DB: "dev_b_email"
  SUPPORT_EMAIL: "care@viwell.com"
  OrgId: "779485866"
  DepartmentId: "730549000000820185"
  ZohoClientId: "1000.M6DGGY0Q49ZI1MC8UTPBFIUFH3XF3P"

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
