apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  EmailHost: "email-smtp.us-east-2.amazonaws.com"
  EmailPort: "465"
  EmailAccountType: "SES"
  ENV: "stagging"
  DB: "Stagging-email"
  SUPPORT_EMAIL: "care@viwell.com"
  KSA_OBJECT_STORAGE_BUCKET_NAME: "viwell-email-templates-staging"
  KSA_OBJECT_STORAGE_REGION: "us-east-1"
  GLOBAL_OBJECT_STORAGE_BUCKET_NAME: "viwell-email-templates-staging"
  GLOBAL_OBJECT_STORAGE_REGION: "us-east-1"
  KSA_OBJECT_STORAGE_BUCKET_NAMESPACE: "viwell-email-templates-staging"

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
