name: api-gateway
replicaCount: 2
AppVersion: 726c3b0-93

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/backendmain
  #repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/api-gateway
  pullPolicy: IfNotPresent
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 8080
  targetport: 80

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
namespace: 'dev'

##for liveness and readiness
path: '/health'
port: 8080
