name: progress
replicaCount: 1
AppVersion: prod-02903f3

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/progress
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30024
  targetport: 30024

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'sec'

##for liveness and readiness
path: '/health'
port: 30024
