name: viwell-seed
replicaCount: 1
AppVersion: "ksa-dev-9be2a4f-21"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/viwell-seed
  pullPolicy: Always
  tag: ""

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 80
  targetport: 80

# resources: 
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:   
namespace: "ksa-dev"
  
##for liveness and readiness
path: "/"
port: 80


