apiVersion: v1
data:
  VAR: "INPUT"
  SQL_DB_NAME: "dev_aggregates"
  ENV: "dev"
  LOG_TOPIC: "dev_log_topic"
kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
