name: reward
replicaCount: 1
AppVersion: prod-stagging-c425536-28

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/reward
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30030
  targetport: 30030

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage:
namespace: 'sec'

##for liveness and readiness
path: '/health'
port: 30030
