apiVersion: v1
data:
  # VAR: "INPUT"
  # SQL_DB_NAME: "dev_attribute"
  # ENV: "dev"
  # KAFKA_CONSUMER_GROUP_ID: 'dev_attribute'


kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
