name: viwell-seed
replicaCount: 1
AppVersion: "dev-9aefc3a-104"

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/viwell-seed
  pullPolicy: IfNotPresent
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 80
  targetport: 80

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'dev'

##for liveness and readiness
path: '/'
port: 80
