apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "30010"
  HOST: "0.0.0.0"
  DB: "Stagging-category"
  SEND_UPDATE_CATEGORY_EVENT: "staging_send_update_category_event"
  SEND_DELETE_COLLECTION_CATEGORY: "staging_send_delete_collection_category"
  SEND_UPDATE_PILLAR_EVENT: "staging_send_update_pillar_event"
  SEND_DEACTIVATE_PILLAR_EVENT: "staging_send_deactivate_pillar_event"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "2"

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
