apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.name }}
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  DB: "viwell-activity"
  AdminHost: "portal.viwell.app"
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: "https://link.viwell.app"
  SEND_DELETE_COLLECTION_CATEGORY: "send_delete_collection_category"
  SEND_UPDATE_CLIENT_EVENT: "send_update_client_event"
