apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "30014"
  HOST: "0.0.0.0"
  NODE_ENV: "false"
  MIN_POOL_SIZE: "2"
  MAX_POOL_SIZE: "4"
  DB: "Stagging-organization"
  USER_STORE_DB: "Stagging-user-store"
  SEND_UPDATE_CLIENT_EVENT: "staging_send_update_client_event"

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
