apiVersion: v1
data:
  ENV: 'dev'
  
 
  DYNAMIC_LINK_DOMAIN_URI_PREFIX: 'link.viwell.app'
  USER_STORE_DB: 'viwell-user-store'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  VAR: 'INPUT'
  DB: 'viwell-push-notification'
  KAFKA_CONSUMER_GROUP_ID: 'dev_push-notification'

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
