apiVersion: v1
data:
  VAR: 'INPUT'
  ENV: 'stagging'
  SEND_DELETE_COLLECTION_CATEGORY: 'send_delete_collection_category'
  SEND_UPDATE_CLIENT_EVENT: 'send_update_client_event'
  PORT: "3009"
  HOST: "0.0.0.0"
  DB: "Stagging-pillar"
  SEND_UPDATE_PILLAR_EVENT: "staging_send_update_pillar_event"
  SEND_DEACTIVATE_PILLAR_EVENT: "staging_send_deactivate_pillar_event"

kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
