name: avatar
replicaCount: 1
AppVersion: 146-a131371

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/backendmain
    #repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/avatar
  pullPolicy: IfNotPresent
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30012
  targetport: 30012

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
namespace: 'dev'

##for liveness and readiness
path: '/health'
port: 30012
