name: habits
replicaCount: 1

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/habits
  pullPolicy: Always
  tag: ""

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30045
  targetport: 30045

# resources: 
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage:   
namespace: "prod"
  
##for liveness and readiness
path: "/health"
port: 30045


