name: email
replicaCount: 1
AppVersion: 259-f22164c

image:
  repository: 814880204573.dkr.ecr.me-central-1.amazonaws.com/backendmain
  pullPolicy: Always
  email: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30042
  targetport: 30042

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercenemaile:
namespace: 'prod'

##for liveness and readiness
path: '/health'
port: 30042
