name: personalisation
replicaCount: 1
AppVersion: 187-afc6a37

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/backendmain
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30027
  targetport: 30027

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'stagging'

##for liveness and readiness
path: '/health'
port: 30027
